# Pré Processamento


In [111]:
import numpy as np
import pandas as pd

#df de dataframe
df = pd.read_csv('/content/drive/MyDrive/MLcP_udemy/heart_tratado.csv',
                        sep = ';', encoding = 'utf-8')

print(df.head())
print(df.shape)

   Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140        289.0          0     Normal    172   
1   49   F           NAP        160        180.0          0     Normal    156   
2   37   M           ATA        130        283.0          0         ST     98   
3   48   F           ASY        138        214.0          0     Normal    108   
4   54   M           NAP        150        195.0          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
(917, 12)


## Transformando as variáveis categóricas nominais em variáveis categóricas ordinais

In [112]:
df2 = pd.DataFrame.copy(df)

df2.Sex.replace({'M': 0, 'F': 1}, inplace = True)
df2.ChestPainType.replace({'TA': 0, 'ATA' : 1, 'NAP' : 2, 'ASY' : 3}, inplace = True)
df2.RestingECG.replace({'Normal' : 0, 'ST' : 1, 'LVH' : 2}, inplace = True)
df2.ExerciseAngina.replace({'N' : 0, 'Y': 1}, inplace = True)
df2.ST_Slope.replace({'Up' : 0, 'Flat' : 1, 'Down' : 2}, inplace = True)

df2.head()

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    0              1        140        289.0          0           0   
1   49    1              2        160        180.0          0           0   
2   37    0              1        130        283.0          0           1   
3   48    1              3        138        214.0          0           0   
4   54    0              2        150        195.0          0           0   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         0             0  
1    156               0      1.0         1             1  
2     98               0      0.0         0             0  
3    108               1      1.5         1             1  
4    122               0      0.0         0             0

## Atributos previsores e alvo

In [113]:
# previsores: argumentos utilizados pra descobrir o alvo

previsores = df2.iloc[:, 0:11].values
# iloc: localiza / ":": todas as linhas
# 0:11": intervalo. na prática vai de 0 até 10, tipo um for i < 11
# .values: formato de array/matriz

previsores

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]])

In [114]:
# alvo/target/classe:
alvo = df2.iloc[:, 11].values
# quando nao tem intervalo, ele pega o argumento q tu pediu: 11

alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

## Análise das escalas dos atributos (Escalonamento)

In [115]:
# Padronização: utiliza a média e o desvio padrão como referência (vamos utilizar)
# Normalização: utiliza os valores máximos e mínimos como referência

from sklearn.preprocessing import StandardScaler # standard scaler = escala de padronização

previsores_esc = StandardScaler().fit_transform(previsores)
previsores_esc
# agora tudo varia em torno de 0, 1

array([[-1.43220634, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       [-0.47805725,  1.9368261 , -0.27058012, ..., -0.82431012,
         0.10625149,  0.59651863],
       [-1.75025603, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       ...,
       [ 0.37007527, -0.51630861,  0.80354095, ...,  1.21313565,
         0.29380223,  0.59651863],
       [ 0.37007527,  1.9368261 , -1.34470119, ..., -0.82431012,
        -0.83150225,  0.59651863],
       [-1.64423947, -0.51630861, -0.27058012, ..., -0.82431012,
        -0.83150225, -1.05109458]])

In [116]:
previsoresdf = pd.DataFrame(previsores_esc)

In [117]:
previsoresdf.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean   1.859654e-16  7.748558e-18  1.046055e-16  7.767929e-16 -1.869340e-16   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -2.704405e+00 -5.163086e-01 -2.418822e+00 -2.920572e+00 -2.994023e+00   
25%   -6.900904e-01 -5.163086e-01 -2.705801e-01 -6.971063e-01 -5.745784e-01   
50%    5.202558e-02 -5.163086e-01  8.035410e-01 -1.412398e-01  0.000000e+00   
75%    6.881250e-01 -5.163086e-01  8.035410e-01  4.146267e-01  4.194568e-01   
max    2.490407e+00  1.936826e+00  8.035410e-01  3.749826e+00  6.721265e+00   

                 5           6             7             8             9   \
count  9.170000e+02  917.000000  9.170000e+02  9.170000e+02  9.170000e+02   
mean   4.649135e-17    0.000000 -5.114048e-16 -1.046055e-16  7.748558e-17   
std    1.000546e+00    1.000546  1.000546e+00  1.000546e+00  1.000546e+00   
min   -5.517333e-01   -0.749818 -3.016886e+00 -8.243101e-01 -3.269662e+00   
25%   -5.517333e-01   -0.749818 -6.596226e-01 -8.243101e-01 -8.315022e-01   
50%   -5.517333e-01   -0.749818  4.755658e-02 -8.243101e-01 -2.688500e-01   
75%   -5.517333e-01    0.491306  7.547357e-01  1.213136e+00  5.751284e-01   
max    1.812470e+00    1.732430  2.561971e+00  1.213136e+00  4.982571e+00   

                 10  
count  9.170000e+02  
mean  -3.874279e-17  
std    1.000546e+00  
min   -1.051095e+00  
25%   -1.051095e+00  
50%    5.965186e-01  
75%    5.965186e-01  
max    2.244132e+00

## Codificação de variáveis categóricas automaticamente

In [118]:
# LabelEncoder: transformação de variáveis categóricas em numéricas
from sklearn.preprocessing import LabelEncoder

previsores2 = df.iloc[:, 0:11].values
previsores2

array([[40, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 'M', 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 'F', 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 'M', 'NAP', ..., 'N', 0.0, 'Up']], dtype=object)

In [119]:
previsores2[:, 1] = LabelEncoder().fit_transform(previsores2[:,  1])
previsores2[:, 2] = LabelEncoder().fit_transform(previsores2[:,  2])
previsores2[:, 6] = LabelEncoder().fit_transform(previsores2[:,  4])
previsores2[:, 8] = LabelEncoder().fit_transform(previsores2[:,  8])
previsores2[:,10] = LabelEncoder().fit_transform(previsores2[:, 10])
# transformando apenas as colunas categóricas

previsores2

array([[40, 1, 1, ..., 0, 0.0, 2],
       [49, 0, 2, ..., 0, 1.0, 1],
       [37, 1, 1, ..., 0, 0.0, 2],
       ...,
       [57, 1, 0, ..., 1, 1.2, 1],
       [57, 0, 1, ..., 0, 0.0, 1],
       [38, 1, 2, ..., 0, 0.0, 2]], dtype=object)

## OneHotEncoder: criação de variáveis Dummy/fictícias

In [120]:
# se 0 for azul, 1 for verde e 2 for vermelho. 2 pessoas gostam de vermelho e 2 gostam de azul.
# a média de cores seria verde? não. isso é uma categoria, não um valor.
# o algoritmo não pode entender como valores maiores ou menores, e sim como diferentes.
# pra isso, criamos uma espécie de sequência, onde azul na verdade é 0-0-1, verde é 0-1-0 e vermelho é 1-0-0
# ele entende como diferentes, mas não como maiores/menores.

# con: deixa a tabela feia kkkkkkkkkkkkkkkkkkk
# ele criaria 3 colunas no lugar de uma, nesse exemplo.

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# parametros ColumnTransformer:
## name: nome dado a transformacao
## transformer: tipo de transformador (vamos usar o OneHotEncoder)
## columns: colunas que vao ser transformadas
## remainder: qq acontece com as outras colunas nao relacionadas: drop(padrão): exclui /// passthrough: mantém
## sparse_threshold: parametro de classificaçao de matrizes esparsas. default 0.3
## n_jobs: número de trabalhos a serem executados em paralelo. default nenhum
## transformer_weights: definição de pesos ao transformadores.
## verbose: True se quiser q a execução apareça na tela

previsores3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1,2,6,8,10])],
                                remainder = 'passthrough').fit_transform(previsores)

previsores3.shape

(917, 20)

In [121]:
previsores3

array([[  1. ,   0. ,   0. , ...,   0. , 172. ,   0. ],
       [  0. ,   1. ,   0. , ...,   0. , 156. ,   1. ],
       [  1. ,   0. ,   0. , ...,   0. ,  98. ,   0. ],
       ...,
       [  1. ,   0. ,   0. , ...,   0. , 115. ,   1.2],
       [  0. ,   1. ,   0. , ...,   0. , 174. ,   0. ],
       [  1. ,   0. ,   0. , ...,   0. , 173. ,   0. ]])

In [122]:
previsores3df = pd.DataFrame(previsores3)
previsores3df.head()
## ainda falta o escalonamento

0    1    2    3    4    5    6    7    8    9    10   11   12   13    14  \
0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  40.0   
1  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  49.0   
2  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  37.0   
3  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  48.0   
4  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  54.0   

      15     16   17     18   19  
0  140.0  289.0  0.0  172.0  0.0  
1  160.0  180.0  0.0  156.0  1.0  
2  130.0  283.0  0.0   98.0  0.0  
3  138.0  214.0  0.0  108.0  1.5  
4  150.0  195.0  0.0  122.0  0.0

In [123]:
from sklearn.preprocessing import StandardScaler
previsores3_esc = StandardScaler().fit_transform(previsores3)
previsores3_esc

array([[ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.38333943, -0.83150225],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         0.75473573,  0.10625149],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -1.52395266, -0.83150225],
       ...,
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -0.85606123,  0.29380223],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         1.46191489, -0.83150225],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.42262716, -0.83150225]])

In [124]:
previsores3df = pd.DataFrame(previsores3_esc)
previsores3df

0         1         2         3         4         5         6   \
0    0.516309 -0.516309 -0.229810  2.073784 -0.531524 -1.085425  0.815013   
1   -1.936826  1.936826 -0.229810 -0.482210  1.881384 -1.085425  0.815013   
2    0.516309 -0.516309 -0.229810  2.073784 -0.531524 -1.085425 -1.226974   
3   -1.936826  1.936826 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
4    0.516309 -0.516309 -0.229810 -0.482210  1.881384 -1.085425  0.815013   
..        ...       ...       ...       ...       ...       ...       ...   
912  0.516309 -0.516309  4.351412 -0.482210 -0.531524 -1.085425  0.815013   
913  0.516309 -0.516309 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
914  0.516309 -0.516309 -0.229810 -0.482210 -0.531524  0.921298  0.815013   
915 -1.936826  1.936826 -0.229810  2.073784 -0.531524 -1.085425 -1.226974   
916  0.516309 -0.516309 -0.229810 -0.482210  1.881384 -1.085425  0.815013   

           7         8         9         10        11        12        13  \
0   -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
1   -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
2    2.037569 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
3   -0.490781 -0.507826 -1.213136  1.213136 -0.869888  0.998910 -0.271607   
4   -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   
..        ...       ...       ...       ...       ...       ...       ...   
912 -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
913 -0.490781 -0.507826  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
914 -0.490781 -0.507826 -1.213136  1.213136 -0.869888  0.998910 -0.271607   
915 -0.490781  1.969177  0.824310 -0.824310 -0.869888  0.998910 -0.271607   
916 -0.490781 -0.507826  0.824310 -0.824310  1.149573 -1.001091 -0.271607   

           14        15        16        17        18        19  
0   -1.432206  0.414627  0.832075 -0.551733  1.383339 -0.831502  
1   -0.478057  1.526360 -1.212261 -0.551733  0.754736  0.106251  
2   -1.750256 -0.141240  0.719543 -0.551733 -1.523953 -0.831502  
3   -0.584074  0.303453 -0.574578 -0.551733 -1.131075  0.575128  
4    0.052026  0.970493 -0.930931 -0.551733 -0.581047 -0.831502  
..        ...       ...       ...       ...       ...       ...  
912 -0.902124 -1.252973  0.363191 -0.551733 -0.188170  0.293802  
913  1.536257  0.636973 -0.968441  1.812470  0.165420  2.356860  
914  0.370075 -0.141240 -2.131275 -0.551733 -0.856061  0.293802  
915  0.370075 -0.141240 -0.161960 -0.551733  1.461915 -0.831502  
916 -1.644239  0.303453 -1.306038 -0.551733  1.422627 -0.831502  

[917 rows x 20 columns]

In [125]:
previsores3df.describe()

0             1             2             3             4   \
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02   
mean  -1.472226e-16  1.084798e-16  6.973702e-17 -3.874279e-17  3.874279e-17   
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00   
min   -1.936826e+00 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
25%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
50%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
75%    5.163086e-01 -5.163086e-01 -2.298105e-01 -4.822104e-01 -5.315237e-01   
max    5.163086e-01  1.936826e+00  4.351412e+00  2.073784e+00  1.881384e+00   

                 5             6             7           8             9   \
count  9.170000e+02  9.170000e+02  9.170000e+02  917.000000  9.170000e+02   
mean   1.937139e-17 -9.298269e-17  1.549712e-17    0.000000 -4.261707e-17   
std    1.000546e+00  1.000546e+00  1.000546e+00    1.000546  1.000546e+00   
min   -1.085425e+00 -1.226974e+00 -4.907810e-01   -0.507826 -1.213136e+00   
25%   -1.085425e+00 -1.226974e+00 -4.907810e-01   -0.507826 -1.213136e+00   
50%    9.212982e-01  8.150134e-01 -4.907810e-01   -0.507826  8.243101e-01   
75%    9.212982e-01  8.150134e-01 -4.907810e-01   -0.507826  8.243101e-01   
max    9.212982e-01  8.150134e-01  2.037569e+00    1.969177  8.243101e-01   

                 10            11          12            13            14  \
count  9.170000e+02  9.170000e+02  917.000000  9.170000e+02  9.170000e+02   
mean   4.261707e-17 -3.874279e-17    0.000000  8.523413e-17  1.859654e-16   
std    1.000546e+00  1.000546e+00    1.000546  1.000546e+00  1.000546e+00   
min   -8.243101e-01 -8.698879e-01   -1.001091 -2.716072e-01 -2.704405e+00   
25%   -8.243101e-01 -8.698879e-01   -1.001091 -2.716072e-01 -6.900904e-01   
50%   -8.243101e-01 -8.698879e-01    0.998910 -2.716072e-01  5.202558e-02   
75%    1.213136e+00  1.149573e+00    0.998910 -2.716072e-01  6.881250e-01   
max    1.213136e+00  1.149573e+00    0.998910  3.681787e+00  2.490407e+00   

                 15            16            17            18            19  
count  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  9.170000e+02  
mean   7.884157e-16  3.014189e-15 -1.549712e-17 -5.114048e-16 -1.859654e-16  
std    1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  1.000546e+00  
min   -2.920572e+00 -2.994023e+00 -5.517333e-01 -3.016886e+00 -3.269662e+00  
25%   -6.971063e-01 -5.745784e-01 -5.517333e-01 -6.596226e-01 -8.315022e-01  
50%   -1.412398e-01  3.198360e-15 -5.517333e-01  4.755658e-02 -2.688500e-01  
75%    4.146267e-01  4.194568e-01 -5.517333e-01  7.547357e-01  5.751284e-01  
max    3.749826e+00  6.721265e+00  1.812470e+00  2.561971e+00  4.982571e+00

## Resumo do Pré-Processamento

*   alvo: variável que se pretende atingir
*   previsores: categóricas em numéricas manualmente, sem escalonar
*   previsores_esc: anterior escalonada
*   previsores2: categóricas em numéricas pelo labelencoder
*   previsores3: transformadas pelo labelencoder e onehotencoder sem escalonar
*   previsores3_esc: anterior escalonada

## Redução de dimensionalidade
o objetivo é selecionar os melhores componentes/atributos do algoritmo, através da análise das variáveis.

Análise dos Componentes Principais (PCA)
- Seleção de característica: seleciona os melhores atributos e utiliza sem transformações. <- vamos ver
- Encontra relações dos melhores atributos e cria novos atributos. <- não supervisionada

In [126]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4) # svd_solver = default = auto.
previsores_pca = pca.fit_transform(previsores2)

print(previsores_pca)
print(pca.explained_variance_ratio_) # quantos % cada variavel "explica"
print(sum(pca.explained_variance_ratio_)) # total

[[  63.66913591  -36.15530336   10.70874169   -5.86818331]
 [ -88.33452678  -13.96179505   31.64896876    8.1501846 ]
 [  55.56003824   33.91094586  -12.42903182   -3.13304186]
 ...
 [-146.19353157   23.3765646    -2.4227271    -0.95013064]
 [ -11.6450827   -35.90602791    4.822686     -1.58901204]
 [ -96.15967905  -35.71488472   12.06824762    9.07518472]]
[0.80349548 0.1147184  0.05422839 0.01543371]
0.9878759813246939


In [127]:
# Kernel PCA
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components=4, kernel='rbf')
previsores_kernel = kpca.fit_transform(previsores2)
print(previsores_kernel)


[[-0.00181259 -0.00238789 -0.00338153 -0.00259073]
 [-0.00181267 -0.002388   -0.00338169 -0.00259088]
 [-0.00181259 -0.00238789 -0.00338153 -0.00259073]
 ...
 [-0.0018126  -0.0023879  -0.00338154 -0.00259075]
 [-0.00181263 -0.00238794 -0.00338161 -0.0025908 ]
 [-0.00181259 -0.00238789 -0.00338153 -0.00259073]]


In [128]:
# Análise do Discriminante Linear (LDA):
# supervisionado, aplicada em situações com muitos atributos previsores
# e também com o atributo alvo com muitas classes

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=1)
previsores_lda = lda.fit_transform(previsores2, alvo)
print(previsores_lda)
print(lda.explained_variance_ratio_)

[[-1.41861202]
 [-1.44798089]
 [-0.89302068]
 [ 0.50548253]
 [-1.49419307]
 [-1.71626967]
 [-2.28530852]
 [-1.2903633 ]
 [ 1.00004587]
 [-1.75599554]
 [-2.57806354]
 [ 1.05206896]
 [-1.45339052]
 [ 1.01361571]
 [-2.50862382]
 [-0.71193591]
 [-0.2981697 ]
 [-2.36518404]
 [ 0.52635905]
 [ 0.07389132]
 [-2.89794123]
 [-0.26180032]
 [-2.29663563]
 [ 1.01497095]
 [-1.72346865]
 [-2.08919773]
 [ 1.67150217]
 [-0.9175985 ]
 [-1.76988531]
 [-1.3666736 ]
 [-0.43222087]
 [-1.49605533]
 [ 0.63280785]
 [ 0.33315649]
 [-2.27466711]
 [-1.4638305 ]
 [ 2.51648773]
 [-2.08932227]
 [-1.56053047]
 [ 0.29110345]
 [-1.88271775]
 [-0.19002084]
 [-1.4850352 ]
 [-1.73734859]
 [ 0.95390653]
 [ 0.7034779 ]
 [-1.23261258]
 [-1.49414465]
 [-0.69798373]
 [-0.06680884]
 [ 1.33337756]
 [ 0.61973817]
 [-0.46942125]
 [-2.14220789]
 [ 0.20747459]
 [-2.30231223]
 [ 0.90164561]
 [-0.58787005]
 [-0.33330151]
 [ 1.59408819]
 [-1.48339854]
 [-2.64744961]
 [-0.94491724]
 [ 1.19147694]
 [-2.15146014]
 [-1.99697714]
 [-1.55812

## Salvando as variáveis (atributos)

In [129]:
import pickle

# cria um arquivo
arq1 = open('heart.pkl', 'wb')
# escreve no arquivo
pickle.dump(alvo, arq1)
# fecha o arquivo
arq1.close()

In [130]:
arq2 = open('heart.pkl', 'rb')
alvo_lido = pickle.load(arq2)
alvo_lido

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

# Base de Treino e Teste

parâmetros:

arrays: nomes dos arrays previsores e alvo

test_size: tamanho em porcentagem dos dados de teste (o restante vai ser treino, ou vice versa se definir o train_size)


train_size: =================================  treino
_ _ _ _ _ _ default: none (mas calcula se definir algum)

random_state: nomeação de um estado aleatório

shuffle: embaralhamento dos dados aleatorios, associado com o random_state

stratify: possibilidade de dividir os dados de forma estratificada, default é none: nesse caso é mantida a proporção de 30% de zeros e 70% de 1 no dataframe, por exemplo.




In [131]:
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size=0.3,
                                                        random_state = 0)

print(x_treino.shape)
print(x_teste.shape)
print(y_treino.shape)
print(y_teste.shape)

(641, 11)
(276, 11)
(641,)
(276,)


# Naive Bayes


In [132]:
from sklearn.naive_bayes import GaussianNB # variacao 'gaussian' da naive bayes

naive = GaussianNB()
naive.fit(x_treino, y_treino) # insert nos dados de treino

GaussianNB()

In [133]:
previsoes_naive = naive.predict(x_teste) # cria a variavel de previsoes

previsoes_naive

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0])

In [134]:
y_teste # pra comparar com as previsoes

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [135]:
# pra calcular a taxa de acerto dele
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score(y_teste, previsoes_naive)
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive)*100))

# previsores     : 84.42
# previsores_esc : 84.42
# previsores2    : 84.06
# previsores3    : 84.78
# previsores3_esc: 84.78

Acurácia: 84.42%


In [136]:
# era 0 e ele disse 0 | era x e ele disse y
# era y e ele disse x | era 1 e ele disse 1

confusion_matrix(y_teste, previsoes_naive)

array([[102,  19],
       [ 24, 131]])

In [137]:
# precision: verdadeiros positivos / (verdadeiros positivos + falsos positivos)
# recall: taxa de identificacao correta
# f1-score: media da precisao e recall
# support: aparicoes na base de dados

print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83       121
           1       0.87      0.85      0.86       155

    accuracy                           0.84       276
   macro avg       0.84      0.84      0.84       276
weighted avg       0.85      0.84      0.84       276



In [138]:
previsoes_treino = naive.predict(x_treino)
accuracy_score(y_treino, previsoes_treino)

# pra ver se a porcentagem de treino/teste ta parecida. se a de treino for muito elevada,
# ele ta viciado no treino. nao ta legal a separacao de treino/teste

0.8361934477379095

# Validação Cruzada

testa com diferentes grupos pra ver se a separação ficou boa

talvez a separação de treino/teste tenha sido ruim

In [162]:
from sklearn.model_selection import KFold, cross_val_score

# separando os dados em 'folds' (grupos)
kfold = KFold(n_splits = 30, shuffle = True, random_state = 5)

# criando o modelo
#modelo = GaussianNB()
#modelo = SVC(kernel='linear', random_state=1, C=30)
#modelo = LogisticRegression(random_state=1, max_iter=500, penalty="l2",tol=0.0001, C=1, solver="lbfgs")
#modelo = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p=1)
#modelo = DecisionTreeClassifier(criterion='entropy', random_state=0, max_depth=3)
#modelo = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state=0, max_depth=4)
#modelo = XGBClassifier(max_depth=2, learning_rate=0.05, n_estimators=250, objective='binary:logistic', random_state=3)
#modelo = lgb.LGBMClassifier(num_leaves=250,objective='binary',max_depth=2,learning_rate=.05,max_bin=100)
modelo = CatBoostClassifier(task_type='CPU', iterations=100, learning_rate=0.1, depth=8,random_state=5, eval_metric="Accuracy")

resultado = cross_val_score(modelo, previsores_esc, alvo, cv = kfold)

print("Acurácia Média: %.2f%%" % (resultado.mean()*100))

0:	learn: 0.8803612	total: 2.47ms	remaining: 245ms
1:	learn: 0.8758465	total: 4.72ms	remaining: 231ms
2:	learn: 0.8837472	total: 6.79ms	remaining: 219ms
3:	learn: 0.8927765	total: 8.83ms	remaining: 212ms
4:	learn: 0.8792325	total: 9.3ms	remaining: 177ms
5:	learn: 0.8803612	total: 11.5ms	remaining: 181ms
6:	learn: 0.8893905	total: 13.6ms	remaining: 181ms
7:	learn: 0.8860045	total: 15.6ms	remaining: 180ms
8:	learn: 0.8927765	total: 17.6ms	remaining: 178ms
9:	learn: 0.8950339	total: 20.2ms	remaining: 182ms
10:	learn: 0.8950339	total: 22.5ms	remaining: 182ms
11:	learn: 0.8961625	total: 24.9ms	remaining: 183ms
12:	learn: 0.8972912	total: 27.2ms	remaining: 182ms
13:	learn: 0.8972912	total: 29.6ms	remaining: 182ms
14:	learn: 0.8995485	total: 32ms	remaining: 181ms
15:	learn: 0.9006772	total: 34.9ms	remaining: 183ms
16:	learn: 0.9029345	total: 37.2ms	remaining: 181ms
17:	learn: 0.9040632	total: 39.5ms	remaining: 180ms
18:	learn: 0.9018059	total: 40.3ms	remaining: 172ms
19:	learn: 0.9051919	tota

 se tiver muito diferente é porque a separação de treino/teste nao ficou boa

85.17% na validacao cruzada -84.78% (naive bayes previsores3_esc)

85.92% na validacao cruzada -86.23% (SVC kernel linear, c = 30)

85.84% na regressao logistica -86.23 (random_state=1, max_iter=500, penalty="l2",tol=0.0001, C=1, solver="lbfgs")

85.84% no knn -84.06 (n_neighbors=7, metric='minkowski', p=1) previsores3_esc ou previsores_esc

83.32% na arvore de decisao -83.7 (criterion='entropy', random_state=0, max_depth=3) previsores3_esc

85.92% no random forest -86.59 (n_estimators=150, criterion='entropy', random_state=0, max_depth=4) previsores

87.13% no XGBoost -87.68 (max_depth=2, learning_rate=0.05, n_estimators=250, objective='binary:logistic', random_state=3) previsores

85.94% LGBM -87.32 (num_leaves:250,objective:'binary',max_depth:2,learning_rate:.05,max_bin:100) previsores_esc

88.00% CatBoost -86.96 CatBoostClassifier(task_type='CPU', iterations=100, learning_rate=0.1, depth=8,random_state=5, eval_metric="Accuracy") (previsores proprios)

# Máquinas de Vetores de Suporte (SVM)


In [139]:
from  sklearn.svm import SVC # support vector classification

# kernel comumente utilizados: rbf, linear, poly, sigmoid, (e se for quadrado) precomputed
svm = SVC(kernel='linear', random_state=1, C=30)
svm.fit(x_treino, y_treino)


previsoes_svm = svm.predict(x_teste)
previsoes_svm

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [140]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm)*100))

#   C=2
#previsores & kernel rbf      : 67.3
#previsores & kernel linear   : 84.42 <--- continuando com esse
#previsores & kernel poly     : 67.39
#previsores & kernel sigmoid  : 55.43

#   C=10
#previsores & kernel linear   : 84.42

#   C=20
#previsores & kernel linear   : 85.51

#   C=30 <--- continuando com esse
#previsores & kernel linear   : 85.87

#   C=50
#previsores & kernel linear   : 85.87




#   previsores_esc
# c = 30 & kernel linear   : 84.42

#   previsores2
# c = 30 & kernel linear   : 84.78

#   previsores3
# c = 30 & kernel linear   : 86.23 <-- campeao

#   previsores3_esc
# c = 30 & kernel linear   : 85.87


Acurácia: 85.87%


In [141]:
confusion_matrix(y_teste, previsoes_svm)

array([[ 98,  23],
       [ 16, 139]])

In [142]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.86      0.81      0.83       121
           1       0.86      0.90      0.88       155

    accuracy                           0.86       276
   macro avg       0.86      0.85      0.86       276
weighted avg       0.86      0.86      0.86       276



In [143]:
previsoes_treino = svm.predict(x_treino)
accuracy_score(y_treino, previsoes_treino)

0.8549141965678627

# Regressão Logística

In [144]:
from sklearn.linear_model import LogisticRegression

logistica = LogisticRegression(random_state=1, max_iter=500, penalty="l2",
                               tol=0.0001, C=1, solver="lbfgs") # atençao pro solver entender a penalty
# max_iter: numero maximo de iteraçoes ate ele parar de 'treinar'
# tol: tolerancia minima (qnd chegar nessa taxa de diferença ele para)

logistica.fit(x_treino, y_treino)

LogisticRegression(C=1, max_iter=500, random_state=1)

In [145]:
print(logistica.intercept_)
print()
print(logistica.coef_)

[-3.33268446]

[[ 0.0123781  -1.27430395  0.66527539  0.00315881  0.00427309  0.92061278
   0.09485448 -0.01172447  1.02708424  0.24925175  1.64750739]]


In [146]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [147]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_logistica)*100))

## c=1, lbfgs, l2 (os outros ficaram piores ainda ou nao mudaram nada)
# max_iter = 200: 85.14%
# max_iter = 500: 85.51% <--
# max_iter = 800: 85.51%

## max_iter = 500:
# previsores     : 85.51%
# previsores_esc : 85.87%
# previsores2    : 85.51%
# previsores3    : 86.23%
# previsores3_esc: 86.23%


Acurácia: 85.51%


In [148]:
confusion_matrix(y_teste, previsoes_logistica)

array([[ 99,  22],
       [ 18, 137]])

In [149]:
print(classification_report(y_teste, previsoes_logistica))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       121
           1       0.86      0.88      0.87       155

    accuracy                           0.86       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.86      0.85       276



In [150]:
accuracy_score(y_treino, logistica.predict(x_treino))

0.8486739469578783

# KNN (aprendizagem baseada em instancias)


In [151]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p=1)
knn.fit(x_treino, y_treino)

# previsores, minkowski, n_neigh 7, p 1: 69.93%

# previsores_esc: 84.06%
# previsores2    : 67.39 vs 78.78 no treino?
# previsores3    : 72.46 vs 81.12 no treino?????
# previsores3_esc: 84.06%

## esse knn é terrível quando nao ta escalonado

KNeighborsClassifier(n_neighbors=7, p=1)

In [152]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [153]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia1: %.2f%%" % (accuracy_score(y_teste, previsoes_knn)*100))
print("Acurácia2: %.2f%%" % (accuracy_score(y_treino, knn.predict(x_treino))*100))

Acurácia1: 69.93%
Acurácia2: 79.88%


In [154]:
print(classification_report(y_teste, previsoes_knn))

              precision    recall  f1-score   support

           0       0.67      0.63      0.65       121
           1       0.72      0.75      0.74       155

    accuracy                           0.70       276
   macro avg       0.69      0.69      0.69       276
weighted avg       0.70      0.70      0.70       276



# Arvore de Decisão

In [155]:
from sklearn.tree import DecisionTreeClassifier

arvore = DecisionTreeClassifier(criterion='entropy', random_state=0, max_depth=3)
arvore.fit(x_treino, y_treino)
previsoes_arvore = arvore.predict(x_teste)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Acurácia1: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore)*100))

Acurácia1: 83.70%


# Random Forest

In [157]:
from sklearn.ensemble import RandomForestClassifier

floresta = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state=0, max_depth=4)
floresta.fit(x_treino, y_treino)
previsoes_floresta = floresta.predict(x_teste)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Acurácia1: %.2f%%" % (accuracy_score(y_teste, previsoes_floresta)*100))

Acurácia1: 86.59%


# XGBoost (eXtreme Gradient Boosting)

In [ ]:
x_treino

In [158]:
from xgboost import XGBClassifier

xgb = XGBClassifier(max_depth=2, learning_rate=0.05, n_estimators=250, objective='binary:logistic', random_state=3)
xgb.fit(x_treino, y_treino)
previsoes_xgb = xgb.predict(x_teste)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_xgb)*100))

Acurácia: 87.32%


# LightGBM (Light Gradient Boosting Machine)
(esse cara tem mais de 100 hiperparametros de ajuste)

In [ ]:
!pip install lightgbm
# instalar pq nao é padrao do google colab

In [ ]:
import lightgbm as lgb

# no lgbm tem q criar um dataset pro treino
dataset = lgb.Dataset(x_treino, label=y_treino)

# e tem q entrar os parametros como um dicionario ... entao vamo criar
parametros = {
    'num_leaves':250,
    'objective':'binary',
    'max_depth':2,
    'learning_rate':.05,
    'max_bin':100
}

lgbm=lgb.train(parametros, dataset,num_boost_round=150)

previsoes_lgbm = lgbm.predict(x_teste)

for i in range (0, previsoes_lgbm.size):
  previsoes_lgbm[i] = 1 if previsoes_lgbm[i] >= .5 else 0

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_lgbm)*100))

# CatBoost

In [105]:
!pip install catboost

In [106]:
from catboost import CatBoostClassifier

# o catboost brinca sozinho com os previsores, e administraria sozinho os seus 100 hiperparametros
previsores4 = df.iloc[:, 0:11]
alvo4 = df.iloc[:,11]

from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores4, alvo4, test_size = 0.3, random_state = 0)

categoricas = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
catboost = CatBoostClassifier(task_type='CPU', iterations=100, learning_rate=0.1, depth=8,
                              random_state=5, eval_metric="Accuracy")

catboost.fit(x_treino, y_treino, cat_features=categoricas, plot=True, eval_set=(x_teste, y_teste))

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Acurácia1: %.2f%%" % (accuracy_score(y_teste, catboost.predict(x_teste))*100))
print("Acurácia2: %.2f%%" % (accuracy_score(y_treino, catboost.predict(x_treino))*100))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.8861154	test: 0.7789855	best: 0.7789855 (0)	total: 8.43ms	remaining: 834ms
1:	learn: 0.8689548	test: 0.7934783	best: 0.7934783 (1)	total: 13.7ms	remaining: 673ms
2:	learn: 0.8471139	test: 0.7971014	best: 0.7971014 (2)	total: 15.3ms	remaining: 494ms
3:	learn: 0.8549142	test: 0.8043478	best: 0.8043478 (3)	total: 19.9ms	remaining: 477ms
4:	learn: 0.8517941	test: 0.8043478	best: 0.8043478 (3)	total: 23.5ms	remaining: 446ms
5:	learn: 0.8486739	test: 0.8043478	best: 0.8043478 (3)	total: 26.9ms	remaining: 422ms
6:	learn: 0.8580343	test: 0.8115942	best: 0.8115942 (6)	total: 30.5ms	remaining: 405ms
7:	learn: 0.8642746	test: 0.8043478	best: 0.8115942 (6)	total: 33.9ms	remaining: 390ms
8:	learn: 0.8533541	test: 0.8043478	best: 0.8115942 (6)	total: 38.3ms	remaining: 387ms
9:	learn: 0.8611544	test: 0.8115942	best: 0.8115942 (6)	total: 42.5ms	remaining: 382ms
10:	learn: 0.8642746	test: 0.8079710	best: 0.8115942 (6)	total: 50.3ms	remaining: 407ms
11:	learn: 0.8658346	test: 0.8043478	best:

# Otimização de Hiperparâmetros

In [ ]:
from sklearn.metrics import roc_auc_score # utilizado na otimização de hiperparametros
from sklearn.model_selection import GridSearchCV # metodo de otimizacao
from sklearn.ensemble import GradientBoostingClassifier # algoritmo novo pra brincar

gbm = GradientBoostingClassifier(random_state=0)

# determinando as modificacoes dos hiperparametros
param_grid = dict(
    n_estimators=[20,50,100,250],
    learning_rate=[0.05,0.1,0.5],
    max_depth=[1,2,3,4,5],
)

grid_search = GridSearchCV(gbm, param_grid, scoring='roc_auc', cv=4)
grid_search.fit(x_treino, y_treino)
grid_search.best_params_

In [ ]:
resultado = pd.DataFrame(grid_search.cv_results_)
resultado.sort_values(by='mean_test_score', ascending=False, inplace=True)
resultado[['param_max_depth', 'param_learning_rate','param_n_estimators','mean_test_score','std_test_score']].head()

# Salvando dados para deploy

In [53]:
previsores

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]])

In [54]:
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,

In [55]:
np.savetxt('previsores.csv', previsores, delimiter=',')

In [56]:
np.savetxt('alvo.csv', alvo, delimiter=',')